

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


//import CalculatorServer;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.RemoteException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;


/**
 *
 * @author User
 */
public class CalculatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        jButton7.setText("jButton7");

        jButton8.setText("jButton8");

        jButton9.setText("jButton9");

        jButton10.setText("jButton10");

        jButton11.setText("jButton11");

        jButton12.setText("jButton12");

        jButton13.setText("jButton13");

        jButton14.setText("jButton14");

        jButton15.setText("jButton15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton4)
                                .addComponent(jButton5))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jButton11))
                                .addComponent(jButton10))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jButton8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton14))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jButton7)
                            .addGap(38, 38, 38)
                            .addComponent(jButton13))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton7)
                    .addComponent(jButton13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton8)
                    .addComponent(jButton14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton9)
                    .addComponent(jButton15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton12))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTextField1.getAccessibleContext().setAccessibleName("display");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private JButton zeroBtn;
    private JButton oneBtn;
    private JButton twoBtn;
    private JButton threeBtn;
    private JButton fourBtn;
    private JButton fiveBtn;
    private JButton sixBtn;
    private JButton sevenBtn;
    private JButton eightBtn;
    private JButton nineBtn;
    
    private JButton equalBtn;
    private JButton plus;
    private JButton minus;
    private JButton power;
    private JButton sinus;
    private JButton cosinus;
    private JButton multiply;
    private JButton divide;
    private JButton decimalBtn;
    private JButton factorBtn;
    private JPanel btnPanel;
    private JTextField display;
    private Object lastBtn;
    private Calculator calc;
    double num1 = 0;
    double num2 = 0;
    public CalculatorGUI(){
                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                setBounds(100, 100, 450, 300);
		display=new JTextField();
		display.setEditable(false);
		btnPanel=new JPanel();
		add(display, BorderLayout.NORTH);
                btnPanel.setLayout(new GridLayout(4,4));
		add(btnPanel, BorderLayout.CENTER);
                
                JButton oneBtn=new JButton("1");
		oneBtn.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                display.setText(display.getText() + "1");
                            } 
                });
                JButton twoBtn=new JButton("2");
		twoBtn.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                display.setText(display.getText() + "2");
                            } 
                });
                JButton threeBtn=new JButton("3");
		threeBtn.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                display.setText(display.getText() + "3");
                            } 
                });
                JButton fourBtn=new JButton("4");
		fourBtn.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                display.setText(display.getText() + "4");
                            } 
                });
                JButton fiveBtn=new JButton("5");
		fiveBtn.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                display.setText(display.getText() + "5");
                            } 
                });
                JButton sixBtn=new JButton("6");
		sixBtn.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                display.setText(display.getText() + "6");
                            } 
                });
                JButton sevenBtn=new JButton("7");
		sevenBtn.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                display.setText(display.getText() + "7");
                            } 
                });
                JButton eightBtn=new JButton("8");
		eightBtn.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                display.setText(display.getText() + "8");
                            } 
                });
                JButton nineBtn=new JButton("9");
		nineBtn.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                display.setText(display.getText() + "9");
                            } 
                });
               
        
                JButton zeroBtn=new JButton("0");
		zeroBtn.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                              display.setText(display.getText() + "0");
                            }
                });
                JButton decimalBtn=new JButton(".");
		decimalBtn.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                display.setText(display.getText() + ".");
                            } 
                });
                
                JButton equalBtn=new JButton("=");
		equalBtn.addActionListener(new java.awt.event.ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (display.getText().equals("")) return;
                        double b = Double.parseDouble(display.getText());
                
                        if (lastBtn == plus) {
                            try {
                                display.setText(Double.toString(calc.sum(num1, num2)));
                            } catch (RemoteException ex) {
                                Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else if(lastBtn == minus) {
                            try {
                                display.setText(Double.toString(calc.sub(num1, num2)));
                            } catch (RemoteException ex) {
                                Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else if(lastBtn == multiply) {
                            try {
                                display.setText(Double.toString(calc.mul(num1, num2)));
                            } catch (RemoteException ex) {
                                Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else if(lastBtn == divide) {
                            try {
                                display.setText(Double.toString(calc.div(num1, num2)));
                            } catch (RemoteException ex) {
                                Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else if (lastBtn == power) {
                            try {
                                display.setText(Double.toString(calc.pow(num1, num2)));
                            } catch (RemoteException ex) {
                                Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
                            }
                }
                    }
                    }) ;
                btnPanel.add(zeroBtn);
                btnPanel.add(oneBtn);
                btnPanel.add(twoBtn);
                btnPanel.add(threeBtn);
                btnPanel.add(fourBtn);
                btnPanel.add(fiveBtn);
                btnPanel.add(sixBtn);
                btnPanel.add(sevenBtn);
                btnPanel.add(eightBtn);
                btnPanel.add(nineBtn);
                btnPanel.add(decimalBtn);
		btnPanel.add(equalBtn);
		JPanel panel2=new JPanel();
		panel2.setLayout(new BoxLayout(panel2, BoxLayout.PAGE_AXIS));
		
		JButton plus=new JButton("+");
		plus.addActionListener(new java.awt.event.ActionListener() { 
                   // private Object CalculatorServer;
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                
                            } 
                });
                panel2.add(plus);
		JButton minus=new JButton("-");
		minus.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                            
                            } 
                });
                panel2.add(minus);
		JButton multiply=new JButton("*");
		multiply.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                            
                            } 
                });
                panel2.add(multiply);
		JButton divide=new JButton("/");
		divide.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                            
                            } 
                });
		panel2.add(divide);
		
		JButton sinus=new JButton("sin");
		sinus.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt){
                                if (display.getText().equals("")) return;
                                num1 = Double.parseDouble(display.getText());
                                lastBtn = evt.getSource();
                                try {
                                    display.setText(Double.toString(calc.sin(num1)));
                                } catch (RemoteException ex) {
                                    Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                });
		panel2.add(sinus);
		JButton cosinus=new JButton("cos");
		cosinus.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                if (display.getText().equals("")) return;
                                num1 = Double.parseDouble(display.getText());
                                lastBtn = evt.getSource();
                                try {
                                    display.setText(Double.toString(calc.cos(num1)));
                                } catch (RemoteException ex) {
                                    Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } 
                });
		panel2.add(cosinus);
		JButton power=new JButton("pow");
		power.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                
                            } 
                });
                panel2.add(power);
                JButton factorBtn=new JButton("n!");
		factorBtn.addActionListener(new java.awt.event.ActionListener() { 
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                if (display.getText().equals("")) return;
                                num1 = Double.parseDouble(display.getText());
                                lastBtn = evt.getSource();
                                try {
                                    display.setText(Double.toString(calc.factor(num1)));
                                } catch (RemoteException ex) {
                                    Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } 
                });
                panel2.add(factorBtn);
                add(panel2, BorderLayout.EAST);
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CalculatorGUI calc = new CalculatorGUI();
                calc.setSize(350, 350);
                new CalculatorGUI().setVisible(true);
            }
        });
    }
   
 
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
